apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-reader
  namespace: simplilearn
rules:
- apiGroups: ["", "extensions", "apps"]   
  resources: [”deployments”,”pods”,”services”]
  verbs: [“get”, “list”,”watch”, ”create”, ”update”, ”delete”,“patch”]
